### ISSUE TITLE
Old but...

### ISSUE THREAD

**Issue by Earnestly** [wybiral/tiny-elf#1]
Here's an example of creating a successively smaller ELF until arriving at 45 bytes: http://www.muppetlabs.com/~breadbox/software/tiny/teensy.html

**Comment by wybiral** [comment]
That one is really cool, but it just exits with status code 42 instead of printing anything. This one has to do two system calls, which makes it harder to squeeze into the header, and store the "Merry Christmas!" string.

**Comment by Earnestly** [comment]
Oh yeah, it only achieves that size by doing very little, thought it might be interesting nevertheless. o/
